version: "3.9"

services:
  mysql:
    image: koncetz/mysql-custom
    restart: always
    ports:
      - 3306:3306
    secrets:
      - db_root_userpass
      - db_name
      - db_username
      - db_userpass
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_userpass
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_username
      MYSQL_PASSWORD_FILE: /run/secrets/db_userpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: koncetz/phpmyadmin-custom
    depends_on:
      - mysql
    restart: always
    ports:
      - 8080:80
    secrets:
      - db_root_userpass
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_userpass
    volumes:
      - phpmyadmin_data:/etc/phpmyadmin
    networks:
      - default
      - proxy

  web:
    image: koncetz/web-custom
    depends_on:
      - mysql
    restart: always
    ports:
      - 8000:80
    networks:
      - default
      - proxy

  proxy:
    image: koncetz/proxy-custom
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy

volumes:
  mysql_data: {}
  phpmyadmin_data: {}

networks:
  default:
    external: false
  proxy:
    external: true

secrets:
  db_root_userpass:
    file: ./secrets/db_root_userpass.txt
  db_name:
    file: ./secrets/db_name.txt
  db_username:
    file: ./secrets/db_username.txt
  db_userpass:
    file: ./secrets/db_userpass.txt
